title: PBSHelp Constitution & Docs
description: Auburn University PBSHelp – system constitution, architecture, security, and implementation notes.
theme: minima  # stable, built-in theme with nav + search-ready structure
markdown: kramdown
highlighter: rouge

# Set these for correct links on GitHub Pages
url: "https://ecg0068.github.io"
baseurl: ""

# Show repo links in header/footer
github:
  is_project_page: true
  repository_url: https://github.com/ecg0068/PBSHelp-Documentation

# Minima theme options (optional)
minima:
  skin: classic
  social_links:
    - { platform: github,  user_url: "https://github.com/ecg0068" }

# Exclude editor/system clutter
exclude:
  - ".obsidian/"
  - "Thumbs.db"
  - ".DS_Store"
